name: test before merging into master

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [14.x]
    runs-on: ${{ matrix.os }}
    # https://zenn.dev/ryo_kawamata/articles/github-actions-specific-branch
    if: contains(github.head_ref, 'feature/') || contains(github.head_ref, 'fix/') || contains(github.head_ref, 'hotfix/') || contains(github.head_ref, 'feature/release/v')
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-v${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run test
        run: yarn test:ci
